In [1]:
##Задание №3:
##Реализовать методы сортировки строк числовой матрицы в соответствии с
##заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
##временем стандартной функции сортировки. Испытания проводить на сгенерированных
##матрицах.

In [2]:
import numpy as np 
import random
import copy

m = input("Введите число строк: ")
n = input("Введите число столбцов: ")
min_lim = input("Введите min элементов: ")
max_lim = input("Введите max элементов: ")

def check(num):
    try:
        int(num)
        return True
    except ValueError:
        return False 

if (check(m) == False):
    m = 50;
if (check(n) == False):
    n = 50;
if (check(min_lim) == False):
    min_lim = -250;
if (check(max_lim) == False):
    max_lim = 1000+(5);
    
m = int(m); n = int(n); min_lim = int(min_lim); max_lim = int(max_lim);
    
print (m,n,min_lim,max_lim)

def creatMarix():
    matrix = np.zeros([int(m),int(n)])
    for i in range(int(m)):
        for j in range(int(n)):
            matrix[i][j] = round(random.random() * (max_lim - min_lim) + min_lim)
    return matrix
    
ARRAY= creatMarix()
print (ARRAY)

matrix_2 = copy.deepcopy(ARRAY);
matrix0 = copy.deepcopy(ARRAY); 
matrix1 = copy.deepcopy(ARRAY);

Введите число строк: 5
Введите число столбцов: 5
Введите min элементов: 
Введите max элементов: 69
5 5 -250 69
[[  68. -243. -148. -212. -242.]
 [-205. -153. -154.   45. -140.]
 [-228. -209.   15. -146. -108.]
 [  63.  -48.   29.  -30.  -28.]
 [  16. -128.    4. -162.  -70.]]


In [3]:
#Сортировка выбором
import time
def selection_sort(ARRAY ):
    for k in ARRAY:
        n = len(k)
        i = 0
        while (i < n- 1):
            j = i + 1
            x = i
            while (j < n):
                if k[x] > k[j]:
                    x = j
                j+=1
            k[i], k[x] = k[x], k[i]
            i+=1
    return ARRAY

stime = time.time()
ARRAY=selection_sort(ARRAY)
print("Время выполнения : ", time.time() - stime)
for i in ARRAY:
    print("\n")
    for j in i:
        print(j, end = " ")

Время выполнения :  0.0


-243.0 -242.0 -212.0 -148.0 68.0 

-205.0 -154.0 -153.0 -140.0 45.0 

-228.0 -209.0 -146.0 -108.0 15.0 

-48.0 -30.0 -28.0 29.0 63.0 

-162.0 -128.0 -70.0 4.0 16.0 

In [4]:
##Сортировка вставками
def insert_sort(ARRAY):
    for k in ARRAY:
        for i in range(len(k)):
            j = i - 1
            key = k[i]
            while k[j] > key and j >= 0:
                k[j + 1] = k[j]
                j-=1
            k[j + 1] = key
    return ARRAY

stime = time.time()
ARRAY=insert_sort(ARRAY)
print("Время выполнения : ", time.time() - stime)
for i in ARRAY:
    print("\n")
    for j in i:
        print(j, end = " ")

Время выполнения :  0.0


-243.0 -242.0 -212.0 -148.0 68.0 

-205.0 -154.0 -153.0 -140.0 45.0 

-228.0 -209.0 -146.0 -108.0 15.0 

-48.0 -30.0 -28.0 29.0 63.0 

-162.0 -128.0 -70.0 4.0 16.0 

In [5]:
## Сортировка обменом
def bubble_sort(ARRAY):
    for k in ARRAY:
        flag = True
        while flag:
            flag = False
            for i in range(len(k) - 1):
                if k[i] > k[i + 1]:
                    k[i], k[i + 1] = k[i+1], k[i]
                    flag = True
    return ARRAY

stime = time.time()
ARRAY=bubble_sort(ARRAY)
print("Время выполнения : ", time.time() - stime)
for i in ARRAY:
    print("\n")
    for j in i:
        print(j, end = " ")

Время выполнения :  0.0


-243.0 -242.0 -212.0 -148.0 68.0 

-205.0 -154.0 -153.0 -140.0 45.0 

-228.0 -209.0 -146.0 -108.0 15.0 

-48.0 -30.0 -28.0 29.0 63.0 

-162.0 -128.0 -70.0 4.0 16.0 

In [6]:
##Cортировка Шелла
def shell_sort(ARRAY):
    for k in ARRAY:
        x = len(k) // 2
        while x:
            for i, y in enumerate(k):
                while i >= x and k[i - x] > y:
                    k[i] = k[i - x]
                    i -= x
                k[i] = y
            x = 1 if x == 2 else int(x * 5.0 / 11)
    return ARRAY


stime = time.time()
ARRAY=shell_sort(ARRAY)
print("Время выполнения : ", time.time() - stime)
for i in ARRAY:
    print("\n")
    for j in i:
        print(j, end = " ")

Время выполнения :  0.0


-243.0 -242.0 -212.0 -148.0 68.0 

-205.0 -154.0 -153.0 -140.0 45.0 

-228.0 -209.0 -146.0 -108.0 15.0 

-48.0 -30.0 -28.0 29.0 63.0 

-162.0 -128.0 -70.0 4.0 16.0 

In [7]:
##Быстрая сортировка
def get_index(ARRAY, x, y):
    p = ARRAY[(x + y) // 2]
    i = x - 1
    j = y + 1
    while True:
        i += 1
        while ARRAY[i] < p:
            i += 1
        j -= 1
        while ARRAY[j] > p:
            j -= 1
        if i >= j:
            return j
        ARRAY[i] , ARRAY[j] = ARRAY[j], ARRAY[i]

def sorting(ARRAY):
    def _quick_sort(ARRAY, x, y):
        if x < y:
            index = get_index(ARRAY, x, y)
            _quick_sort(ARRAY, x, index)
            _quick_sort(ARRAY, index + 1, y)
    _quick_sort(ARRAY, 0,len(ARRAY) - 1)

def quick_sort(ARRAY):
    for k in ARRAY:
        sorting(k)
    return ARRAY
    
stime = time.time()
ARRAY = quick_sort(ARRAY)
print("Время выполнения : ", time.time() - stime)
for i in ARRAY:
    print("\n")
    for j in i:
        print(j, end = " ")

Время выполнения :  0.0


-243.0 -242.0 -212.0 -148.0 68.0 

-205.0 -154.0 -153.0 -140.0 45.0 

-228.0 -209.0 -146.0 -108.0 15.0 

-48.0 -30.0 -28.0 29.0 63.0 

-162.0 -128.0 -70.0 4.0 16.0 

In [8]:
##Турнирная сортировка
stime = time.time()

def heapify(arr, n, i):
    largest = i 
    l = 2 * i + 1   
    r = 2 * i + 2   

    if l < n and arr[i] < arr[l]:
        largest = l

    if r < n and arr[largest] < arr[r]:
        largest = r

    if largest != i:
        arr[i],arr[largest] = arr[largest],arr[i] 

        heapify(arr, n, largest)

def heapSort(arr):
    n = len(arr)

    for i in range(n, -1, -1):
        heapify(arr, n, i)

    for i in range(n-1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]  
        heapify(arr, i, 0)
        
arr = copy.deepcopy(ARRAY[:][0])
print (arr, "\n")
heapSort(arr)
n = len(arr)
print (arr, "\n")

print("Время выполнения : ", time.time() - stime)

[-243. -242. -212. -148.   68.] 

[-243. -242. -212. -148.   68.] 

Время выполнения :  0.0009982585906982422
