In [1]:
##Задание№2

##Написать генератор случайных матриц(многомерных), который принимает 
##опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
##матрицы, а min_lim и max_lim - минимальное и максимальное значение для
##генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
##значения:

##m = 50
##n = 50
##min_limit = -250
##max_limit = 1000 + (номер своего варианта)



In [2]:
import numpy as np 
import random
import copy

m = input("Введите число строк: ")
n = input("Введите число столбцов: ")
min_lim = input("Введите min элементов: ")
max_lim = input("Введите max элементов: ")

def check(num):
    try:
        int(num)
        return True
    except ValueError:
        return False 

if (check(m) == False):
    m = 50;
if (check(n) == False):
    n = 50;
if (check(min_lim) == False):
    min_lim = -250;
if (check(max_lim) == False):
    max_lim = 1000+(5);
    
m = int(m); n = int(n); min_lim = int(min_lim); max_lim = int(max_lim);
    
print (m,n,min_lim,max_lim)

def creatMarix():
    matrix = np.zeros([int(m),int(n)])
    for i in range(int(m)):
        for j in range(int(n)):
            matrix[i][j] = round(random.random() * (max_lim - min_lim) + min_lim)
    return matrix
    
ARRAY = creatMarix()
print (ARRAY)

matrix_2 = copy.deepcopy(ARRAY);
matrix0 = copy.deepcopy(ARRAY); 
matrix1 = copy.deepcopy(ARRAY);

Введите число строк: 12
Введите число столбцов: 12
Введите min элементов: 3
Введите max элементов: 64
12 12 3 64
[[60. 55. 59. 40.  9. 14. 23. 57. 21. 56.  6. 11.]
 [62. 14.  3. 18.  5. 58. 32.  9. 41. 11. 52. 29.]
 [33. 25. 16. 53. 15. 11. 62. 11. 29. 62. 56. 29.]
 [17. 37. 15. 27. 45. 63. 48. 40. 50. 24. 14. 50.]
 [23. 28. 13. 14. 33. 25. 59. 53.  7. 30.  4. 33.]
 [64. 31. 51. 18. 36. 20. 24. 30. 63. 40.  9. 45.]
 [27. 24.  9. 41. 38. 43. 43. 33. 31. 17. 16. 54.]
 [27. 23. 31. 23. 39. 28. 48.  6. 29.  6. 20.  3.]
 [ 9. 29. 50. 59. 57. 20. 31. 63. 32. 37. 43. 54.]
 [39. 14. 40. 23. 64. 10. 14. 57. 15. 39.  9. 47.]
 [47.  7. 36. 23. 26. 32. 28. 53. 48. 19. 17.  4.]
 [61. 14.  8. 30. 55. 18. 19. 43.  8. 50. 54. 23.]]
